### ISSUE TITLE
Any plan to port it to Windows?

### ISSUE THREAD

**Issue by arshcaria** [dell/libsmbios#14]
This util is quite useful. It would be good to port this to Windows. Because Windows utils like Dell command power manager cannot be accessed via command line.

**Comment by superm1** [comment]
FWIW Dell command configure (DCC) can change most of what libsmbios can do.

A port to Windows was started a while back (you'll see lots of references to Win32 stuff in the code) but it has been on hold for a while.

**Comment by arshcaria** [comment]
Hi superm1

I just want to say thanks to you.
I have downloaded dell command configure. Although I cannot find usable thermal mode options in the DCC document/reference, I did find a camera option `--camera`. This fixed the webcam for me. 

I could not use the webcam since a BIOS update recently. It didn't show up in the device manager. In BIOS the `camera` option was already checked, but there seems to be a bug that the webcam was not enabled for some reason. 

I found the `--camera` option for `cctk.exe` by chance. And after running `cctk --camera=enable`, the webcam comes back again!

Thank you!

**Comment by arshcaria** [comment]
BTW, do you know which DCC option is to control the thermal mode?

I have gone through the whole reference list of available options but couldn't find it.

**Comment by superm1** [comment]
Glad DC worked for you.
I don't know that there are thermal options in the interface that DCC uses (or libsmbios for that matter).

If you're not finding a particular option I would recommend you post in the forums.  The social media folks can check with the right team and would have to shepherd the request through.
