### ISSUE TITLE
Dell Precision 7510 keyboard LEDs support broken on Linux

### ISSUE THREAD

**Issue by arcivanov** [dell/libsmbios#17]
There is a problem with Precision 7510 LEDs not being supported on Linux. Seeing that this is an official Dell repository, maybe you have an access to the SMBIOS documentation that would allow to add support for this platform.

Related Linux Kernel issues: 
    https://bugzilla.redhat.com/show_bug.cgi?id=1436686
    https://bugzilla.kernel.org/show_bug.cgi?id=191731

```
bash-4.3$ sudo ./smbios-sys-info
Libsmbios version:      2.3.3
Product Name:           Precision 7510
Vendor:                 Dell Inc.
BIOS Version:           1.10.7
System ID:              0x06D9
Service Tag:            XXXXXX
Express Service Code:   YYYYYYY
Asset Tag:              Not Specified
Property Ownership Tag: 
bash-4.3$ sudo ./smbios-keyboard-ctl -vi
Libsmbios version : 2.3.3
smbios-keyboard-ctl version : 2.3.3

 Capabilities of KeyBoard Illumination on your system: 
-------------------------------------------------------------------
Get Keyboard Illumination Capability: res[smi.cbRES1]=0x0,res[smi.cbRES2]=0x2000143,res[smi.cbRES3]=0x707,res[smi.cbRES4]=0xCFFFF
 Supported USER Selectable Modes : 
         Always OFF
         Auto: Input-activity-based On (illumination level 50%); input-activity based Off
         Auto: Input-activity-based On (illumination level 100%); input-activity based Off

 Supported Keyboard illumination type :  Reserved

 Supports Keyboard illumination on : 
        Any Keystroke
        Touchpad activity
        Pointing stick

 Can configure Keyboard illumination timeout unit in : 
        Seconds
        Minutes
        Hours

 Supported Keyboard light brightness levels :  0

 Maximum acceptable seconds timeout value   :  255

 Maximum acceptable minutes timeout value   :  255

 Maximum acceptable hours timeout value     :  12

 Maximum acceptable days timeout value      :  0
bash-4.3$ sudo ./smbios-keyboard-ctl -vg
Helper function to print current status of keyboard illumination

 Current status of KeyBoard Illumination setting on your system: 
-------------------------------------------------------------------
Get Keyboard Illumination Configuration: res[smi.cbRES1]=0x-2,res[smi.cbRES2]=0x0,res[smi.cbRES3]=0x0
 Info: Unable to fetch Keyboard Illumination Configuration information: Feature Not supported on this system

Get Keyboard illumination Current State: res[smi.cbRES1]=0x0,res[smi.cbRES2]=0xA030100,res[smi.cbRES3]=0xA000000

 Configured mode state: 
         Auto: Input-activity-based On (illumination level 100%); input-activity based Off

 Your Keyboard will illumination on: 
        Any Keystroke
        Touchpad activity

 Keyboard illumination timeout on battery has been set at: 10  Seconds

 Keyboard illumination timeout on AC has been set at: 10  Seconds

 Current setting of ALS value that turns the light on or off: 0
 Current ALS Reading : 0
 Current keyboard light level : 0
```

**Comment by superm1** [comment]
Have you already tried running this with master?  There has been a lot of activity lately specifically around problems with the keyboard backlight.

**Comment by arcivanov** [comment]
The above results are with master.

**Comment by superm1** [comment]
Oh right, I should have looked more closely at your output, you definitely have some of the stuff that was in master present there.

So what's the actual problem?  When you try to select particular modes it is failing?  It see it reading the current mode like it's supposed to.

**Comment by arcivanov** [comment]
@superm1

User-selectable modes work! Yay! I'll use the code here to see if I can update the kernel drivers to get them to set the values properly. 

The timeouts and triggers do not, even though they can be set.

**Comment by arcivanov** [comment]
```
bash-4.3$ sudo ./smbios-keyboard-ctl --set-trigger
Setting Keyboard illumination Triggers 

 Select Keyboard illumination on: 
        Trigger Type            Option
------------------------------------------------
        Any Keystroke            0
        Touchpad activity        1
        Pointing stick           2
Eg: to Select Trigger for [Any Keystroke] and [Touchpad activity] specify your option like this 0,1)
Trigger on -0,1
Triggers Validated Successfully [0, 1]

New trigger parameter set Successfully

bash-4.3$ sudo ./smbios-keyboard-ctl --set-timeout-ac=10s
Setting keyboard illumination timeout value  of:  10s

 Your Keyboard will illumination on: 
        Any Keystroke
        Touchpad activity
        Pointing stick

Old Keyboard illumination battery timeout is: 10  Seconds

Old Keyboard illumination AC timeout is: 10  Seconds

New timeout-ac parameter set Successfully
```

**Comment by arcivanov** [comment]
Notice, that Trigger Type confirmed as stored as [0, 1], but [0, 1, 2] is reflected in `--set-timeout-ac`

**Comment by arcivanov** [comment]
And obviously the light stays on at levels 6 and 8 no matter what.

**Comment by superm1** [comment]
@arcivanov oh Yes, so there is a LKML thread that I posted recently to @pali the information needed to add AC timeout to fix the kernel drivers.  if you've got some time to do it I'm sure @pali would appreciate the help.  Please feel free to CC me (mario.limonciello@dell.com) on the patch too.

Here is the kernel thread:
http://www.spinics.net/lists/platform-driver-x86/msg11195.html

Regarding the trigger stuff, do you actually have a pointing stick on your 7510?  (Forgive me; I don't keep track of which models physically have this feature)

**Comment by arcivanov** [comment]
Yes, I do have a pointing stick. Thanks for the info!

**Comment by superm1** [comment]
I double checked and it's expected behavior that trackpoint and touchpad are grouped.  It's not possible to separate the event streams today.  Setting trackpoint will enable touchpad and vice versa.

Considering this is all expected behavior and the tools are just passing the information I'll mark this closed for libsmbios.
