### ISSUE TITLE
Building of .deb on Ubuntu 17.04

### ISSUE THREAD

**Issue by petr-nehez** [dell/libsmbios#20]
Is there anybody who can help me to make .deb file for Ubuntu 17.04?
I am not able to do it and I would like to use the latest version because of the issue with the keyboard backlight on my Precision 3510.

This is an output I get when I execute `make debs`:

`tmp_dir='mktemp -d /tmp/firmware-tools.XXXXXXXX' ; \`
`make debmagic DEB_TMP_BUILDDIR=${tmp_dir} DIST= DISTTAG= ; \`
`rm -rf ${tmp_dir}`
`make[1]: Entering directory '/home/petr/Downloads/libsmbios-master'`
`[ -n "$DEB_TMP_BUILDDIR" ] || (echo "Must set DEB_TMP_BUILDDIR=/tmp/... for deb and sdeb targets"; exit 1)`
`[ -n "$DIST" ] || (echo "Must set DIST={gutsy,hardy,sid,...} for deb and sdeb targets"; exit 1)`
`Must set DIST={gutsy,hardy,sid,...} for deb and sdeb targets`
`Makefile:4049: recipe for target 'debmagic' failed`
`make[1]: *** [debmagic] Error 1`
`make[1]: Leaving directory '/home/petr/Downloads/libsmbios-master'`

**Comment by superm1** [comment]
So what you'll want to do if you want to use the built in deb building:

I've adjusted a few things, give it another shot.

```
make dist
make debs DIST=zesty
```

The build system is a little weird though.  I think it makes sense to axe these odd Makefile targets (debs and debmagic) and only do builds in docker containers with a docker script.

**Comment by petr-nehez** [comment]
I had some time to give another try, it's better but still no `.deb` file.
First I had to change `pkg/debian/changelog.in` where the first line was updated to contain **2.3.3**.
But then the build still fails see output in [20-0.txt](https://github.com/dell/libsmbios/files/1158479/20-0.txt) and the rest on the screen here [20-1.txt](https://github.com/dell/libsmbios/files/1158481/20-1.txt).

**Comment by sujithshankar** [comment]
I tried with master branch with a few tweaks and through #_dpkg-buildpackage_
Please check if this serves the purpose for you as well.

1. Move the debian folder from pkg/ to root of the source code: #_mv ./pkg/debian ./_
2. From source-root folder, do #_dch_ and update the version in changelog
3. libsmbios-dev and libsmbios-doc are having some issues. So, in _debian/control_ file, comment out the Package section of these two packages.
4. Build packages using  #_dpkg-buildpackage -b_
.deb files of packages will be parent directory.

Have to check how to make libsmbios-dev and libsmbios-doc work with this approach.

**Comment by petr-nehez** [comment]
Sorry for late response but I've been busy during summer time.
It still does not succeed - it fails on missing `out/libsmbios_c++/html/*`.
See the `libsmbios_2.3.3_amd64.build` [here](https://github.com/dell/libsmbios/files/1280046/libsmbios_2.3.3_amd64.build.txt).
