### ISSUE TITLE
SyntaxErrors after building

### ISSUE THREAD

**Issue by Dxhs** [dell/libsmbios#21]
After building with from a git checkout, I can't get any smbios commands to run. 
For instance:

`> smbios-thermal-ctl`
Returns
`File "/usr/local/sbin/smbios-thermal-ctl", line 73`
`return ((num >> (byte_pos*8)) & 0xFF)`
`         ^`
`SyntaxError: invalid syntax`

Different commands yield errors in different files.

I wanted to try the recommended build method, but when executing ./configure.ac I get another syntax error. 
`./configure.ac: line 14: syntax error near unexpected token [release_major_version],'`
`./configure.ac: line 14: m4_define([release_major_version], [2])'`

Any help is appreciated, thanks.

**Comment by superm1** [comment]
What version of python are you using?

**Comment by Dxhs** [comment]
3.6.1

**Comment by superm1** [comment]
so the tools haven't yet been ported to python3 (see https://github.com/dell/libsmbios/issues/7 being open).  @prabhakarpujeri hasn't made any progress on that yet.  If you would like to help, pull requests are welcome.
