### ISSUE TITLE
segmentation fault on set service tag

### ISSUE THREAD

**Issue by bobbyvinon** [dell/libsmbios#23]
server dell r230:

smbios-sys-info --service-tag --set=XXXXXXX

*** Error in `/usr/bin/python': free(): invalid pointer: 0x00007f8c4ed0d5e0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x70bcb)[0x7f8c4fde0bcb]
/lib/x86_64-linux-gnu/libc.so.6(+0x76f96)[0x7f8c4fde6f96]
/lib/x86_64-linux-gnu/libc.so.6(+0x777de)[0x7f8c4fde77de]
/usr/local/lib/libsmbios_c.so.2(token_get_smbios_struct+0x1e1)[0x7f8c4eaf2dc1]
/usr/local/lib/libsmbios_c.so.2(+0x18610)[0x7f8c4eaeb610]
/usr/local/lib/libsmbios_c.so.2(sysinfo_set_service_tag+0x3aa)[0x7f8c4eaee12a]
/usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c)[0x7f8c4ed14038]
/usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x32a)[0x7f8c4ed13a9a]
/usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x2d4)[0x7f8c4ef28224]
/usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x10be5)[0x7f8c4ef27be5]
/usr/bin/python(PyObject_Call+0x43)[0x5606f1aed673]
/usr/bin/python(PyEval_EvalFrameEx+0x60ff)[0x5606f1b06e2f]
/usr/bin/python(PyEval_EvalCodeEx+0x255)[0x5606f1aff535]
/usr/bin/python(+0x115ea8)[0x5606f1b1bea8]
/usr/bin/python(PyObject_Call+0x43)[0x5606f1aed673]
/usr/bin/python(PyEval_EvalFrameEx+0x2b75)[0x5606f1b038a5]
/usr/bin/python(PyEval_EvalCodeEx+0x255)[0x5606f1aff535]
/usr/bin/python(PyEval_EvalFrameEx+0x6968)[0x5606f1b07698]
/usr/bin/python(PyEval_EvalCodeEx+0x255)[0x5606f1aff535]
/usr/bin/python(PyEval_EvalFrameEx+0x61e9)[0x5606f1b06f19]
/usr/bin/python(PyEval_EvalFrameEx+0x5eef)[0x5606f1b06c1f]
/usr/bin/python(PyEval_EvalCodeEx+0x255)[0x5606f1aff535]
/usr/bin/python(PyEval_EvalCode+0x19)[0x5606f1aff2d9]
/usr/bin/python(+0x128e3f)[0x5606f1b2ee3f]
/usr/bin/python(PyRun_FileExFlags+0x82)[0x5606f1b29d52]
/usr/bin/python(PyRun_SimpleFileExFlags+0x19e)[0x5606f1b2989e]
/usr/bin/python(Py_Main+0x6c1)[0x5606f1adaaf1]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7f8c4fd902b1]
/usr/bin/python(_start+0x2a)[0x5606f1ada31a]
======= Memory map: ========

**Comment by superm1** [comment]
Would you mind re-testing this with master?  There's been a few crashers fixed that may have helped it.

**Comment by superm1** [comment]
I'm going to close this one, I'm pretty sure this was fixed with one of the memory leakers fixed targeted to 2.4 release.  So i'm going to close it.  If you still encounter, please re-open and test with master.
