### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by petefwalter** [dell/libsmbios#31]
There's lots of nice bug fixes in git, but latest release is from March, which means the bug fixes are all missing from linux distros (I'm particularly interested in Fedora that ships latest 2.3.3 release). Are there any plans to roll a new release?

**Comment by superm1** [comment]
Yes, there's just a few more issues to be fixed yet. You can see milestones on issues tab.

**Comment by superm1** [comment]
@petefwalter I've got the issues I wanted targeted for 2.4 fixed.  
The remaining things to me:

- I'd appreciate some testing on Fedora with master if you're able to help.  There is a helper script in `./pkg/mk-rel-rpm.sh` that you can use to generate (hopefully) workable RPMs.
- I'm waiting for confirmation on a [problem in Ubuntu](https://bugs.launchpad.net/ubuntu/+source/libsmbios/+bug/1744782) is fixed
- Run through coverity with the new code.

**Comment by superm1** [comment]
The ubuntu problem was confirmed fixed and I've cleaned up coverity.  I'm just looking for verification that the packages work well on an RPM distro.

**Comment by petefwalter** [comment]
Thanks @superm1. I am not in a position to test this right now, but I'll certainly do that once the release is out.

**Comment by superm1** [comment]
Closing with https://github.com/dell/libsmbios/releases/tag/v2.4.0
