### ISSUE TITLE
Improve error handling in libsmbios

### ISSUE THREAD

**Issue by kholia** [dell/libsmbios#32]
I am using libsmbios 2.3.3. The `smbios-get-ut-data` utility crashes when run as a normal user.

```
$ smbios-get-ut-data  # normal user
Libsmbios:    2.3.3
Segmentation fault (core dumped)
```

It would be nice to check if the user has the required privilege level, and exit gracefully if that is not the case.

```
$ sudo smbios-get-ut-data  # as root
Libsmbios:    2.3.3
dumping table header.
dumping table.
dumped table.
table length: 519
```

**Comment by superm1** [comment]
Can you please check with master? I believe this was actually a different problem causing that segfault that was fixed.

**Comment by kholia** [comment]
With `master`,

```
$ git rev-parse HEAD
4fec2add58830d6c580ac3aab1323848a43e8c6b

$ ./out/smbios-get-ut-data
Libsmbios:    2.3.3
Segmentation fault (core dumped)
```

**Comment by superm1** [comment]
Can you give that branch I just submitted a try?  I think that should sort out the problems with this one.

**Comment by kholia** [comment]
The `wip/fix-32 ` branch works quite well :+1: 

```
$ ./out/smbios-get-ut-data 
Libsmbios:    2.3.3
error initializing SMBIOS table
could not read from memory: Permission denied
could not read from memory: Permission denied
```

```
$ git rev-parse HEAD
63396cb5770e2790d270609f6876a8c4fb6a0c84
```

```
$ sudo ./out/smbios-get-ut-data 
Libsmbios:    2.3.3
dumping table header.
dumping table.
dumped table.
table length: 3291
```

**Comment by kholia** [comment]
I recently scanned libsmbios 2.3.3 using Coverity, and I am attaching the report here.

[libsmbios-coverity-scan-results.txt](https://github.com/dell/libsmbios/files/1541344/libsmbios-coverity-scan-results.txt) (scan results).

Some of the Coverity findings in this particular code are false positives, so please ignore them. I believe that this report can help in improving (and possibly hardening) libsmbios.

**Comment by superm1** [comment]
Thanks for sharing. Recently some work went into master from a coverity scan. It should be fairly better. I've been meaning to rescan.

**Comment by superm1** [comment]
I merged fixes-32 today.
