### ISSUE TITLE
Using this lib to change backlight settings on Dell XPS w/ Ubuntu 16.04

### ISSUE THREAD

**Issue by ORESoftware** [dell/libsmbios#4]
I am on Dell XPS 9550 running Ubuntu 16.04 LTS - would like to change the length of time the backlit keyboard is on. I get the feeling this library can help, can you please point me in the right direction? thanks!

**Comment by superm1** [comment]
You'll want to look at https://github.com/dell/libsmbios/blob/master/src/bin/smbios-keyboard-ctl.
It should have an argument for this.
