### ISSUE TITLE
How to update firmware on Dell R815 without RBU?

### ISSUE THREAD

**Issue by paulmenzel** [dell/libsmbios#46]
`DellBiosUpdate` was dropped in commit 0a6ba645 (Drop RBU support). How should the firmware be updated on a Dell R815?

**Comment by superm1** [comment]
All the tools are distributed with the BIOS update for server BIOS.  Eg for R815: http://www.dell.com/support/home/us/en/04/drivers/driversdetails?driverId=JF8YH

Upstream libsmbios is not needed for the update.
