### ISSUE TITLE
Cannot build without help2man

### ISSUE THREAD

**Issue by hughsie** [dell/libsmbios#49]
This is when building as a flatpak when there is no help2man available:

    make[3]: Leaving directory '/run/build/libsmbios_c'
    false --output=out/smbios-sys-info-lite.1 --name=out/smbios-sys-info-lite out/smbios-sys-info-lite
    make[2]: [Makefile:2969: out/smbios-sys-info-lite.1] Error 1 (ignored)
    false --output=out/smbios-get-ut-data.1 --name=out/smbios-get-ut-data out/smbios-get-ut-data
    make[2]: [Makefile:2969: out/smbios-get-ut-data.1] Error 1 (ignored)
    false --output=out/smbios-state-byte-ctl.1 --name=out/smbios-state-byte-ctl out/smbios-state-byte-ctl
    make[2]: [Makefile:2969: out/smbios-state-byte-ctl.1] Error 1 (ignored)
    false --output=out/smbios-upflag-ctl.1 --name=out/smbios-upflag-ctl out/smbios-upflag-ctl
    make[2]: [Makefile:2969: out/smbios-upflag-ctl.1] Error 1 (ignored)
     /usr/bin/mkdir -p '/app/share/man/man1'
     /usr/bin/install -c -m 644 ./out/smbios-sys-info-lite.1 ./out/smbios-get-ut-data.1 ./out/smbios-state-byte-ctl.1 ./out/smbios-upflag-ctl.1 '/app/share/man/man1'
    /usr/bin/install: cannot stat './out/smbios-sys-info-lite.1': No such file or directory
    /usr/bin/install: cannot stat './out/smbios-get-ut-data.1': No such file or directory
    /usr/bin/install: cannot stat './out/smbios-state-byte-ctl.1': No such file or directory
    /usr/bin/install: cannot stat './out/smbios-upflag-ctl.1': No such file or directory

Notice the `false` -- that needs to be conditionalized before trying to build the `.1` files.

**Comment by superm1** [comment]
Is it not possible to install `help2man` while building?  Autotools and I struggled getting it in there in the first place, but yeah I do see the need to conditionalize it.

**Comment by hughsie** [comment]
> Is it not possible to install help2man while building?

Sure you can, but it seems odd to install it, build the man pages, and then just delete them from the ostree.
