### ISSUE TITLE
Prebuilt rpm/deb packages

### ISSUE THREAD

**Issue by michaeljs1990** [dell/libsmbios#5]
I have found a few links online to places where prebuilt packages of libsmbios were available from dell however all of them 404 now. Do you still provide this prebuilt?

**Comment by superm1** [comment]
Unfortunately that was a casualty of the move to GitHub. I think there is a possibility to do some via some continuous integration saving of artifacts, but I haven't researched this myself.

**Comment by michaeljs1990** [comment]
Thanks for the quick response, If i can get the rpm building for me locally i'll see what kind of effort it would take to get it into something like travis.

**Comment by michaeljs1990** [comment]
#6 fixed part of this which is a working RPM. I have tested it on my system and it works awesome so far when setting the asset tag which was my biggest driver for getting this working.

**Comment by herrold** [comment]
Curiously Debian builder matter is in:
   https://github.com/dell/libsmbios/tree/master/docker

but both Debian AND RPM based are at:
   https://github.com/dell/libsmbios/tree/master/pkg

a 'git mv'  and some dits may be in order to get to a Single Point of Truth

**Comment by superm1** [comment]
So I've connected Travis CI build matrix with jobs for both Debian and CentOS dockerfiles. 
https://travis-ci.org/dell/libsmbios
I think this can now be connected with the stuff that lets you upload when tagged:
https://docs.travis-ci.com/user/deployment/releases/

I haven't used that in the past with anything, but it looks promising.

**Comment by superm1** [comment]
Alright I committed https://github.com/dell/libsmbios/commit/9b5dd8781dd60c14308bf3a673872fea4ed45954
We'll see if that works properly when the 2.4 release is tagged.

**Comment by michaeljs1990** [comment]
Awesome work! thanks for getting something in place.

**Comment by superm1** [comment]
Thanks.  @michaeljs1990 btw close to getting a 2.4 release out.  Any testing you can apply with what's in master would be greatly appreciated.

**Comment by superm1** [comment]
Looks like it worked!
https://github.com/dell/libsmbios/releases/tag/v2.4.0
