### ISSUE TITLE
ERROR: Could not manipulate system token.

### ISSUE THREAD

**Issue by rakovskij-stanislav** [dell/libsmbios#55]
Dell Latitude E6430. Ubuntu 18.04, Kernel 4.15

Running: 

> sudo smbios-token-ctl

Getting 29 tokens, and the 30th is error:
```
  Token: 0x007d - LCD Brightness (Value)
ERROR: Could not manipulate system token.
```
I was trying to  'patch' /usr/sbin/smbios-token-ctl and successfully escape LCD token, but after this there is the other 'Could not manipulate system token' with many other tokens

Sum up: Got 70 tokens, blacklisted these tokens:
```
0x007d,"LCD Brightness (Value)"
0x0140,"CPU XD Support (Off)"
0x0141,"CPU XD Support (Enabled)"
0x0146,"USB Wake Support (Off)"
0x0147,"USB Wake Support (Enabled)"
0x014a,"CPU Virtualization (Disabled)"
0x014b,"CPU Virtualization (Enabled)"
0x0152,"Bluetooth Devices (Enabled)"
0x0153,"Bluetooth Devices (Disabled)"
0x017b,"Cellular Radio (Disable)"
```
and it'is not end. I have not found the option to automatically escape broken tokens. Maybe I did something bad and broke something on my notebook?)

PS - my target is make my fan work full speed, 70-80°C without huge load, and over 90-95°C with 2/8 cores used is not pretty good)

**Comment by superm1** [comment]
So there are several tokens that may be filtered from WMI interface in kernel now.  You might be running into problems when these occur.  A patch to `smbios-token-ctl` to handle this situation better would be great.

**Comment by rakovskij-stanislav** [comment]
Hi!

Here is the patch)

```
9,10d8
9,10d8
<   # Some mod by Rakovskij Stanislav, 2018, rakovskij.stanislav@gmail.com
<   #
234,236d231
<         except Exception as e:
<             print("   Kitten exception:", e)
<             print("    Do not worry if this problem is not for every token.\nPossibly you cannot use this token because of your bios does not support it or your OS handle it by self")     
```

If you disallow my greedy 9-10 lines, you can freely cut it)
New 234-237 lines allow to bypass raising the exception.

Waiting for answer,
Rakovskij Stanislav

**Comment by superm1** [comment]
Can you please send it as a PR on Github?  I think the text might need a little massaging too.

**Comment by rakovskij-stanislav** [comment]
Done! (It is my first pull request, so exciting) - https://github.com/dell/libsmbios/pull/56

**Comment by rakovskij-stanislav** [comment]
Investigating the the excluded tokens using this path

Token: 0x007d - LCD Brightness (Value)
Token: 0x0140 - CPU XD Support (Off)
Token: 0x0141 - CPU XD Support (Enabled)
Token: 0x0146 - USB Wake Support (Off)
Token: 0x0147 - USB Wake Support (Enabled)
Token: 0x014a - CPU Virtualization (Disabled)
Token: 0x014b - CPU Virtualization (Enabled)
Token: 0x0152 - Bluetooth Devices (Enabled)
Token: 0x0153 - Bluetooth Devices (Disabled)
Token: 0x017b - Cellular Radio (Disable)
Token: 0x017c - Cellular Radio (Enable)
Token: 0x017f - Wireless LAN (Disable)
Token: 0x0180 - Wireless LAN (Enable)
Token: 0x0181 - Wireless Switch Bluetooth Control (Disable)
Token: 0x0182 - Wireless Switch Bluetooth Control (Enable)
Token: 0x0183 - Wireless Switch Cellular Control (Disable)
Token: 0x0184 - Wireless Switch Cellular Control (Enable)
Token: 0x0185 - Wireless Switch Wireless LAN Control (Disable)
Token: 0x0186 - Wireless Switch Wireless LAN Control (Enable)
Token: 0x0189 - External USB Ports (Disabled)
Token: 0x018a - External USB Ports (Enabled)
Token: 0x0193 - Wireless Switch Changes (Denied)
Token: 0x0194 - Wireless Switch Changes (Permitted)
Token: 0x0198 - Wake on LAN (LAN or WLAN)
Token: 0x019b - Password Bypass (Off)
Token: 0x019c - Password Bypass (Reboot Bypass)
Token: 0x01ce - Sound Device (Auto)
Token: 0x01d8 - Module Bay Device (Disabled)
Token: 0x01d9 - Module Bay Device (Enabled)
Token: 0x01de - Microphone (Disabled)
Token: 0x01df - Microphone (Enabled)
Token: 0x01e1 - Keyboard Illumination (Off)
Token: 0x01ea - Core-Based Turbo Mode (Off)
Token: 0x01eb - Core-Based Turbo Mode (Enabled)
Token: 0x02ea - Keyboard Backlight Level (25)
Token: 0x02eb - Keyboard Backlight Level (50)
Token: 0x02ec - Keyboard Backlight Level (75)
Token: 0x02f6 - Keyboard Backlight Level (100)
Token: 0x0325 - Signed Firmware Update (Enable)

```
$ sudo /usr/sbin/smbios-token-ctl | grep "Kitten" | wc -l
39
$ sudo /usr/sbin/smbios-token-ctl | grep "Token" | wc -l
210
```
