### ISSUE TITLE
smbios-thermal-ctl: do not require root permissions when reading thermal info

### ISSUE THREAD

**Issue by jsalatas** [dell/libsmbios#68]
Is there a possibility for smbio-thermal-ctl to not require root privileges while reading thermal info? Ie to be able to run the command  `smbios-thermal-ctl  -g` as normal (non-root) user?

Thanks!

**Comment by superm1** [comment]
Thermal calls are not on the whitelist in the kernel to run with capabilities.  You can experiment with adding them to the kernel and running as a user with capabilities.  If that works, you can submit a kernel patch.  From libsmbios side, there is nothing that can be done.

https://github.com/torvalds/linux/blob/master/drivers/platform/x86/dell-smbios-base.c#L49

**Comment by jsalatas** [comment]
FYI: Unfortunately that didn't work, although I added the relevant call (`{0x0000,	CLASS_INFO,		19}`) to the whitelist capabitlities.

It seems that it is not enough as libsmbios tries to read from `/sys/firmware/dmi/tables`:
https://github.com/dell/libsmbios/blob/0cd2e55565cd1c1b8f2bc14fafb690083e278923/src/libsmbios_c/smbios/smbios_linux.c#L111
and
https://github.com/dell/libsmbios/blob/0cd2e55565cd1c1b8f2bc14fafb690083e278923/src/libsmbios_c/smbios/smbios_linux.c#L131

In fact, execution doesn't even reach to the filter part that checks the capabilities if it cannot read the files under `/sys/firmware/dmi/tables`.

Thanks for your help and feedback in any case!
