### ISSUE TITLE
Computer freezes on keyboard illumination token activation on Inspiron 1012 and 1018

### ISSUE THREAD

**Issue by pacien** [dell/libsmbios#76]
(I've reported this to the Dell technical support, but my message has been routed to the french office which couldn't provide me with an answer…)

On the Dell Inspiron 1012 and 1018 laptops, SMBIOS reports supporting keyboard illumination tokens (`0x01e1`, `0x01e2`, `0x01e3`), but activating those causes the SMBIOS call to never return and the machine to freeze (notably at boot).

This can be reproduced on those machines with the following command with libsmbios:
```
sudo smbios-token-ctl --activate -i 0x01e2
```

This looks like a firmware issue.
Would it be possible to publish a BIOS update for this?

Kernel issue: https://bugzilla.kernel.org/show_bug.cgi?id=107651

**Comment by pacien** [comment]
CC: @superm1 
LKML cross-ref: https://lkml.org/lkml/2019/9/22/70

**Comment by superm1** [comment]
I agree this sounds like a firmware problem.
However these are pretty old platforms and unlikely to get any firmware fixes.  I think the right thing to do in this instance is to blacklist these platforms from `dell-laptop`.
