### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [dell/libsmbios#77]
I think that it would be good to flush currently committed changes and make new release :)

**Comment by superm1** [comment]
I recently heard of a memory leak happening in Fedora.  I think once that's figured out flushing a release seems fine.
https://github.com/dell/libsmbios/issues/78

**Comment by superm1** [comment]
@kloczek soon.  Just sorting out a few WMI API problems.

**Comment by superm1** [comment]
tagged a new release today
