### ISSUE TITLE
smbios-thermal-ctl: Info: Unable to Get Thermal Information on this system

### ISSUE THREAD

**Issue by pacho2** [dell/libsmbios#85]
I wanted to check fan configuration options using smbios-thermal-ctl on a Dell Inc. Inspiron 15 7000 Gaming, but it fails with:
# smbios-thermal-ctl -i
Libsmbios version : 2.4.3
smbios-thermal-ctl version : 2.4.3

 Print all the Available Thermal Information of your system: 
-------------------------------------------------------------------
	 Info: Unable to Get Thermal Information on this system

I am unsure about how to fix the problem... I have wmi module loaded and I cannot find anything special in my dmesg output as a hint of something that could be missing.  I attach dmesg output

Thanks
[dmesg.txt](https://github.com/dell/libsmbios/files/4156330/dmesg.txt)

**Comment by superm1** [comment]
Is fan control offered in your BIOS setup?

**Comment by pacho2** [comment]
No, I tried first to control it from BIOS but I didn't find any entry for that :/

**Comment by superm1** [comment]
It's possible your system doesn't support it.  One more thing you can check is using Dell command:
https://www.dell.com/support/article/us/en/04/sln311302/dell-command-configure?lang=en

See if it works there.

**Comment by pacho2** [comment]
Sorry for the delay, I was preparing an ebuild to install it in my distribution (Gentoo)

Sadly it fails to run with:
dell-2017 /opt/dell/dcc # ./cctk 
Error communicating with BIOS - Unable to Get DMI Information!
Status = 0
bool SMBIOSPresent = 0
TableLength = 0

Unable to get BIOS tables or Unknown type encountered!!.

But I can get dmi information with dmidecode command for example, I can attach that output if you want

**Comment by superm1** [comment]
Presumably you ran as root right?
You might need to turn off `SMM mitigations` in BIOS setup if it's on for that tool to work.  Might also go as `Windows SMM mitigations`, don't recall for sure.

**Comment by pacho2** [comment]
Sure, I run as root

Regarding the mitigations, I looked and I thought I didn't see them, but I will recheck

**Comment by superm1** [comment]
On an XPS notebook I have on hand, I checked in BIOS setup where it's listed.  Might be same for you.

It's under "Security", then "SMM Security Mitigation" and there will be a checkbox for it.

**Comment by pacho2** [comment]
I have rechecked but I don't have anything related with SMM :/ 

Maybe because my laptop is from 2017 and that wasn't available yet

**Comment by superm1** [comment]
Yeah, if you can't change it in BIOS setup, can't change it with libsmbios, and DCC doesn't do anything, I'm gonna say your laptop probably won't support this type of control unfortunately.
