### ISSUE TITLE
Executing the "sudo smbios-token-ctl" showed me "StopIteration"

### ISSUE THREAD

**Issue by whsu0202** [dell/libsmbios#86]
While I executed the "sudo smbios-token-ctl" command, the console showed me "StopIteration" as follows.
\----------------------------------------------------------------------------------------
user@user:~$ sudo smbios-token-ctl -i 0x049b
\================================================================================
  Token: 0x049b - unknown (unknown)
  value: bool = true
   Desc: unknown
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/libsmbios_c/smbios_token.py", line 134, in __iter__
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/sbin/smbios-token-ctl", line 475, in <module>
    sys.exit( main() )
  File "/usr/sbin/smbios-token-ctl", line 380, in main
    dumpTokens(tokenTable, tokenXlator, options)
  File "/usr/sbin/smbios-token-ctl", line 214, in dumpTokens
    for token in tokenTable:
RuntimeError: generator raised StopIteration
\----------------------------------------------------------------------------------------

# System Info:
    - Distributor ID: Ubuntu
    - Description: Ubuntu Focal Fossa
    - Release: 20.04
    - Kernel: Linux u-27469 5.4.0-25-generic
# Build info:
    - 2.4.3

**Comment by Vombato** [comment]
Having the same issue, did you found any luck in figuring out what could cause this?

**Comment by superm1** [comment]
There's certain things the kernel doesn't let you access that probably need to be taken into account.

**Comment by whsu0202** [comment]
Thank you for all your information. It seemed to me that I was using the incorrect Python version to run the script. After I did a double-check and re-installed the Python. Everything works properly. We can close the issue. Thank you!

**Comment by mentatxx** [comment]
Having the same issue, how did you resolve it?
Python 3 is installed
